### PR TITLE
docs (Model #1)

### PR DESCRIPTION
**Pull request by pollend**
I went through and added some documentation to Model. I looked through a couple of your commits and tried to match the format.

### CODE REVIEW

**Comment by haikarainen** [comment]
Hi, first off, I really appreciate your hard work! Thank you!

There are a few inconsistencies here. For example:

https://github.com/haikarainen/kit/pull/17/commits/cd5c9cb712fe1ed64bbb9211fcc2b8a8a441e544#diff-54229bfe8be48ae26656bbc601cfc89fR46

^ That is not a constructor, and it's not for internal use only.

https://github.com/haikarainen/kit/pull/17/commits/cd5c9cb712fe1ed64bbb9211fcc2b8a8a441e544#diff-54229bfe8be48ae26656bbc601cfc89fR142

^ The private member lines do not line up, also the private methods should come before hte private members.

If you fix  those isuses I will merge this . 

Also I would like to add that while I really appreciate contributions, when it comes to cleanup and docs at this point in time I'd rather do all of this myself. This pull request is impressive and you obviously have done your research, but there are a tons of stuff in the code that has to be changed, removed, and altered while cleaning up, which means that any docs htat are written now might get replaced later. Also this is a very large project, and I feel that anyone that has not worked on this project for a long time might miss some things in the docs (and I highly value the quality of the docs).

**Comment by pollend** [comment]
fixed

**Comment by haikarainen** [comment]
You still have the same thing on the other create method (which is also not a constructor, or only for internal use!).

A constructor is a constructor. Easy as that. 

Also, there is no \brief line (you just removed it).

**Comment by pollend** [comment]
yep fixed those couple of problems.

**Comment by haikarainen** [comment]
Sorry still problems. I'll just write the docs for this class myself instead. Thanks though.

**Pull request closed without merging**
